# Generated by Django 5.2.4 on 2025-07-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('family_id', models.CharField(blank=True, max_length=20, null=True)),
                ('show_age', models.BooleanField(default=True)),
            ],
        ),
    ]
